name: qkezz
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313h2cb717b_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - eigen=3.4.0=h59b6b97_0
  - expat=2.7.1=h8ddb27b_0
  - fontconfig=2.14.1=hb33846d_3
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=ha00e802_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9f=ha349fce_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libmpdec=4.0.0=h827c3e9_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libprotobuf=5.29.3=h65a231f_1
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py313h827c3e9_2
  - mkl_fft=1.3.11=py313h827c3e9_0
  - mkl_random=1.2.8=py313hce38976_0
  - numexpr=2.11.0=py313hdb065b2_0
  - numpy=2.3.1=py313ha127e54_0
  - numpy-base=2.3.1=py313haaa8b43_0
  - opencv=4.10.0=py313hba024fa_7
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.0.17=h35632f6_0
  - pandas=2.3.2=py313h42c1672_0
  - pcre2=10.42=h0ff8eda_1
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - python=3.13.7=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313haa95532_0
  - qtbase=6.7.3=hd088775_4
  - setuptools=72.1.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.6=h8880b57_0
prefix: C:\Users\qkezz\.conda\envs\qkezz
